### ISSUE TITLE
can I take over it?

### ISSUE THREAD

**Issue by goenning** [MiniProfiler/node#2]
I'm a big fan of MiniProfiler for .Net, it's just awesome! 
But now that I'm working with node.js, I'd like to be able to use miniprofiler with it as well.

I saw that miniprofiler-node is kind of dead right now, but I'd like to bring it back to life.

Please take a look at [goenning/miniprofiler-node](https://github.com/goenning/miniprofiler-node)
There is still a lot of work to be done here, specially regarding providers, but that's a good start.

If you do allow me, I'd like to take over it. If that's not an option, I'd break the fork and start a new package, but of course, using miniprofiler's ui and giving MiniProfiler the proper credits.

**Comment by SamSaffron** [comment]
personally I am fine with it, I wonder if anyone in Stack Exchange has a say on it? have you tried contacting @goenning  ?

**Comment by goenning** [comment]
@mjibson and @kevin-montrose, could you guys evaluate my request?

**Comment by mjibson** [comment]
Yes, take over. We worked on this but never finished it or got it into a releaseable, documented state.

**Comment by mjibson** [comment]
I've invited you to the repo, and I have no objections to adding you to the top-level org if you need that too. What's your npmjs username so I can transfer ownership there?

**Comment by goenning** [comment]
That would be nice, but not completely necessary right now. I just need someone to enable this repo at travis.

**Comment by mjibson** [comment]
I think I enabled this in travis. But I'm not sure how to verify.

**Comment by goenning** [comment]
it's working, thank you
